// Generated by gencpp from file airsim_ros/DebugSphere.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_MESSAGE_DEBUGSPHERE_H
#define AIRSIM_ROS_MESSAGE_DEBUGSPHERE_H

#include <ros/service_traits.h>


#include <airsim_ros/DebugSphereRequest.h>
#include <airsim_ros/DebugSphereResponse.h>


namespace airsim_ros
{

struct DebugSphere
{

typedef DebugSphereRequest Request;
typedef DebugSphereResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DebugSphere
} // namespace airsim_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::airsim_ros::DebugSphere > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::airsim_ros::DebugSphere&) { return value(); }
};

template<>
struct DataType< ::airsim_ros::DebugSphere > {
  static const char* value()
  {
    return "airsim_ros/DebugSphere";
  }

  static const char* value(const ::airsim_ros::DebugSphere&) { return value(); }
};


// service_traits::MD5Sum< ::airsim_ros::DebugSphereRequest> should match
// service_traits::MD5Sum< ::airsim_ros::DebugSphere >
template<>
struct MD5Sum< ::airsim_ros::DebugSphereRequest>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros::DebugSphere >::value();
  }
  static const char* value(const ::airsim_ros::DebugSphereRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros::DebugSphereRequest> should match
// service_traits::DataType< ::airsim_ros::DebugSphere >
template<>
struct DataType< ::airsim_ros::DebugSphereRequest>
{
  static const char* value()
  {
    return DataType< ::airsim_ros::DebugSphere >::value();
  }
  static const char* value(const ::airsim_ros::DebugSphereRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::airsim_ros::DebugSphereResponse> should match
// service_traits::MD5Sum< ::airsim_ros::DebugSphere >
template<>
struct MD5Sum< ::airsim_ros::DebugSphereResponse>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros::DebugSphere >::value();
  }
  static const char* value(const ::airsim_ros::DebugSphereResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros::DebugSphereResponse> should match
// service_traits::DataType< ::airsim_ros::DebugSphere >
template<>
struct DataType< ::airsim_ros::DebugSphereResponse>
{
  static const char* value()
  {
    return DataType< ::airsim_ros::DebugSphere >::value();
  }
  static const char* value(const ::airsim_ros::DebugSphereResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIRSIM_ROS_MESSAGE_DEBUGSPHERE_H
