// Generated by gencpp from file airsim_ros/TriggerPort.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_MESSAGE_TRIGGERPORT_H
#define AIRSIM_ROS_MESSAGE_TRIGGERPORT_H

#include <ros/service_traits.h>


#include <airsim_ros/TriggerPortRequest.h>
#include <airsim_ros/TriggerPortResponse.h>


namespace airsim_ros
{

struct TriggerPort
{

typedef TriggerPortRequest Request;
typedef TriggerPortResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TriggerPort
} // namespace airsim_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::airsim_ros::TriggerPort > {
  static const char* value()
  {
    return "4b0800f6a99fc8260513e9a5171b5b0f";
  }

  static const char* value(const ::airsim_ros::TriggerPort&) { return value(); }
};

template<>
struct DataType< ::airsim_ros::TriggerPort > {
  static const char* value()
  {
    return "airsim_ros/TriggerPort";
  }

  static const char* value(const ::airsim_ros::TriggerPort&) { return value(); }
};


// service_traits::MD5Sum< ::airsim_ros::TriggerPortRequest> should match
// service_traits::MD5Sum< ::airsim_ros::TriggerPort >
template<>
struct MD5Sum< ::airsim_ros::TriggerPortRequest>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros::TriggerPort >::value();
  }
  static const char* value(const ::airsim_ros::TriggerPortRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros::TriggerPortRequest> should match
// service_traits::DataType< ::airsim_ros::TriggerPort >
template<>
struct DataType< ::airsim_ros::TriggerPortRequest>
{
  static const char* value()
  {
    return DataType< ::airsim_ros::TriggerPort >::value();
  }
  static const char* value(const ::airsim_ros::TriggerPortRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::airsim_ros::TriggerPortResponse> should match
// service_traits::MD5Sum< ::airsim_ros::TriggerPort >
template<>
struct MD5Sum< ::airsim_ros::TriggerPortResponse>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros::TriggerPort >::value();
  }
  static const char* value(const ::airsim_ros::TriggerPortResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros::TriggerPortResponse> should match
// service_traits::DataType< ::airsim_ros::TriggerPort >
template<>
struct DataType< ::airsim_ros::TriggerPortResponse>
{
  static const char* value()
  {
    return DataType< ::airsim_ros::TriggerPort >::value();
  }
  static const char* value(const ::airsim_ros::TriggerPortResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIRSIM_ROS_MESSAGE_TRIGGERPORT_H
