// Generated by gencpp from file airsim_ros/VelCmd.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_MESSAGE_VELCMD_H
#define AIRSIM_ROS_MESSAGE_VELCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace airsim_ros
{
template <class ContainerAllocator>
struct VelCmd_
{
  typedef VelCmd_<ContainerAllocator> Type;

  VelCmd_()
    : header()
    , vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , yawRate(0.0)
    , va(0)
    , stop(0)  {
    }
  VelCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , yawRate(0.0)
    , va(0)
    , stop(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _vz_type;
  _vz_type vz;

   typedef double _yawRate_type;
  _yawRate_type yawRate;

   typedef uint8_t _va_type;
  _va_type va;

   typedef uint8_t _stop_type;
  _stop_type stop;





  typedef boost::shared_ptr< ::airsim_ros::VelCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::airsim_ros::VelCmd_<ContainerAllocator> const> ConstPtr;

}; // struct VelCmd_

typedef ::airsim_ros::VelCmd_<std::allocator<void> > VelCmd;

typedef boost::shared_ptr< ::airsim_ros::VelCmd > VelCmdPtr;
typedef boost::shared_ptr< ::airsim_ros::VelCmd const> VelCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::airsim_ros::VelCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::airsim_ros::VelCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::airsim_ros::VelCmd_<ContainerAllocator1> & lhs, const ::airsim_ros::VelCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.vz == rhs.vz &&
    lhs.yawRate == rhs.yawRate &&
    lhs.va == rhs.va &&
    lhs.stop == rhs.stop;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::airsim_ros::VelCmd_<ContainerAllocator1> & lhs, const ::airsim_ros::VelCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace airsim_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::airsim_ros::VelCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airsim_ros::VelCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros::VelCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros::VelCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros::VelCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros::VelCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::airsim_ros::VelCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a888a503939ba521aed68feee8eab6d";
  }

  static const char* value(const ::airsim_ros::VelCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a888a503939ba52ULL;
  static const uint64_t static_value2 = 0x1aed68feee8eab6dULL;
};

template<class ContainerAllocator>
struct DataType< ::airsim_ros::VelCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "airsim_ros/VelCmd";
  }

  static const char* value(const ::airsim_ros::VelCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::airsim_ros::VelCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Official RMUA simulator definition (see IntelligentUAVChampionshipSimulator/.../VelCmdmsg/VelCmd.msg)\n"
"std_msgs/Header header\n"
"float64 vx\n"
"float64 vy\n"
"float64 vz\n"
"float64 yawRate\n"
"uint8 va\n"
"uint8 stop\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::airsim_ros::VelCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::airsim_ros::VelCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
      stream.next(m.yawRate);
      stream.next(m.va);
      stream.next(m.stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::airsim_ros::VelCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::airsim_ros::VelCmd_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vz: ";
    Printer<double>::stream(s, indent + "  ", v.vz);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yawRate: ";
    Printer<double>::stream(s, indent + "  ", v.yawRate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "va: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.va);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIRSIM_ROS_MESSAGE_VELCMD_H
