(cl:defpackage airsim_ros-msg
  (:use )
  (:export
   "<ALTIMETER>"
   "ALTIMETER"
   "<ANGLERATETHROTTLE>"
   "ANGLERATETHROTTLE"
   "<CARCONTROLS>"
   "CARCONTROLS"
   "<CARSTATE>"
   "CARSTATE"
   "<ENVIRONMENT>"
   "ENVIRONMENT"
   "<GPSYAW>"
   "GPSYAW"
   "<GIMBALANGLEEULERCMD>"
   "GIMBALANGLEEULERCMD"
   "<GIMBALANGLEQUATCMD>"
   "GIMBALANGLEQUATCMD"
   "<POSECMD>"
   "POSECMD"
   "<ROTORPWM>"
   "ROTORPWM"
   "<VELCMD>"
   "VELCMD"
   "<VELCMDGROUP>"
   "VELCMDGROUP"
  ))

